name: Build and push to Docker Hub

on:
  push:
    branches: [ "master", "main", "prod", "production" ]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          node-version: '20'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Client
        run: |
          # Build and tag React client
          docker build -f client/Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/react_go_todos_client:latest -t ${{ secrets.DOCKER_USERNAME }}/react_go_todos_client:${{ github.sha }} ./client
          
          # Push all tags
          docker push ${{ secrets.DOCKER_USERNAME }}/react_go_todos_client:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/react_go_todos_client:${{ github.sha }}

      - name: Build and push Server
        run: |
          # Build and tag Go server
          docker build -f server/Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/react_go_todos_server:latest -t ${{ secrets.DOCKER_USERNAME }}/react_go_todos_server:${{ github.sha }} ./server
          
          # Push all tags
          docker push ${{ secrets.DOCKER_USERNAME }}/react_go_todos_server:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/react_go_todos_server:${{ github.sha }}

      - name: Log out from DockerHub
        run: docker logout